import type { Metadata } from "next";
import "@styles/index.scss";
import AuthLayout from "@/components/layout/AuthLayout";

export const metadata: Metadata = {
    title: "Jayden管理",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AuthLayout>
            {children}
        </AuthLayout>
    );
}
