import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";
import "@styles/index.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Jayden管理",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="jp">
            <body className={inter.className}>
                <Sidebar />
                <div className="l-main-container">
                    <Header />
                    {children}
                </div>
            </body>
        </html>
    );
}
